name: macOS

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: macOS-latest

    strategy:
      matrix:
        perl:
          - static
          - "5.33"
          - "5.32"
          - "5.30"
          - "5.28"
          - "5.26"
          - "5.24"
          - "5.22"
          - "5.20"
          - "5.18"
          - "5.16"
          - "5.14"
          - "5.12"
          - "5.10"
          - "5.8"

    steps:
      - uses: actions/checkout@v2

      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: Cache CPAN modules
        uses: actions/cache@v2
        with:
          path: ~/perl5
          key: ${{ runner.os }}-build-${{ steps.cache-key.outputs.key }}
          restore-keys: |
            ${{ runner.os }}-build-${{ steps.cache-key.outputs.key }}

      - name: Installing dependencies
        run: |
          cpanm Dist::Zilla::App::Command::build

      - name: Build module
        run: |
          dzil build
          perl Makefile.pl
          make

      - name: Test module
        run: make test
